os: Visual Studio 2015
platform: x64
environment:
  global:
    MINICONDA: "C:\\Miniconda36-x64"
    REPO_DIR: httpstan
    PACKAGE_NAME: httpstan
    BUILD_COMMIT: 0.9.0
    WHEELHOUSE_UPLOADER_USERNAME: "stan-worker"
    WHEELHOUSE_UPLOADER_REGION: "IAD"
    WHEELHOUSE_UPLOADER_SECRET:
      secure: 9xnd08h7pp+3ytu6xKKwdo/fT9VXS7GjF6LkgLGynZqWQmZZ1PHDDD2epJa1HJbz
  matrix:
    - PYTHON_VERSION: 3.7

install:
  # check out the desired commit
  - git submodule update --init --recursive
  - cd %REPO_DIR%
  - git fetch origin
  - git checkout %BUILD_COMMIT%

  # setup the environment
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=%PYTHON_VERSION%
  - activate test-env
  - conda install numpy cython scipy matplotlib pandas setuptools libpython m2w64-toolchain -c msys2 -q
  - gcc --version
  - mingw32-make --version

  # Install the build dependencies of the project.
  - pip install -q -r requirements.txt
  - pip install -q -r test-requirements.txt

  - ECHO "Starting to build the wheel"
  # generate required cpp files
  - mingw32-make
  # build the wheel and install it
  - python setup.py --quiet bdist_wheel
  - ps: "ls dist"

  - ECHO "Install generated wheel to test it"
  # Install the generated wheel package to test it
  - pip install -q --pre --no-index --find-links dist/ httpstan

# Not a .NET project, we build the package in the install step instead
build: false

test_script:
  - mkdir empty_folder
  - cd empty_folder
  - python -c "import httpstan"
  - python -m pytest ../tests -v

artifacts:
    - path: "%REPO_DIR%\\dist\\*"

on_success:
  # Upload the generated wheel package to Rackspace
  # On Windows, Apache Libcloud cannot find a standard CA cert bundle so we
  # disable the ssl checks.
  - python -m pip install wheelhouse-uploader
  - python -m wheelhouse_uploader upload --no-ssl-check --local-folder=%REPO_DIR%\dist --no-update-index --region=%WHEELHOUSE_UPLOADER_REGION% httpstan
